language: java
jdk:
  - oraclejdk8
  - openjdk8

sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  CODECOV_TOKEN="f97426b0-741a-4bfb-b0d7-cdbd57b1ab66"
